apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-des
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: infra-des-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: infra-des-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        velero.io/exclude-from-backup: "true"
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      project: default
      sources:
        - repositoryType: git
          repoURL: https://github.com/autstudent/infra-chart
          chart: infra-chart
          targetRevision: main
        - repositoryType: git
          repoURL: https://github.com/autstudent/infra-values
          targetRevision: main
          path: des
      destination:
        namespace: default
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=false
          - PruneLast=true

