apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application-setup-pre
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/autstudent/infra-acm.git
    path: pre
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: {}